
name: 'CI'
on:
  push:
  pull_request:

jobs:
  test123:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test123
        run: |
          ls -la
          ps x -w
